name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm install

      - uses: actions/cache@v3
        with:
          path: /tmp/jest_rt
          key: ${{ hashFiles('**/package-lock.json') }}-${{ matrix.shard }}

      - run: npm run test:unit